### ISSUE TITLE
SSR和SS不能同时安装，我用了别的方式分开装就可以共存了，这时为什么呢

### ISSUE THREAD

**Issue by ckldy** [waylybaye/HyperApp-Guide#102]
SSR和SS不能同时安装，我用了别的方式分开装就可以共存了，这时为什么呢。希望后面能够在里面直接安装，然后两个都能同时使用。

**Comment by waylybaye** [comment]
可以啊，你是不是两个用同一个端口了？不同端口肯定可以的。

**Comment by samy0901** [comment]
可以共存的，參考這篇 "R6250+tomato+ssserver+softether+ssr, 2.4G穩定"
http://www.hkepc.com/forum/viewthread.php?fid=12&tid=2386961
我是改用小米R1D Router，改刷第三方ROM-tomato後，照著作者的步驟，刷成功了"XiaoMiWiFi R1D + Tomato v1.28_140 + SofetEther (L2TPv3/IPsec可用，SSTP無法啟動) + SSR, 2.4G/5GHz WiFi都正常"
只是我把MiWiFi R1D的1TB 2.5"HD硬碟拿掉，裝TOMATO也不需要HD；我改裝上一個SATA 2.5" SSD到 R1D，然後，把SSD的Partition分割sda1 mount到 jffs 使用，其他都能套用原作者的發文了。
