### ISSUE TITLE
HTTP(S)验证

### ISSUE THREAD

**Issue by Thomas4949** [waylybaye/HyperApp-Guide#104]
今天新出的HTTP(S)代理似乎（按照教程上的步骤）没有办法设置账户密码验证啊？如果不能设置的话岂不是谁都可以用？

**Comment by Thomas4949** [comment]
如果不能设置的话用起来岂不是很危险？

**Comment by waylybaye** [comment]
目前是不能的，不过你加了TLS的话机器人是扫不出你的代理的。squid 我会改进一下。

**Comment by waylybaye** [comment]
ref #105

**Comment by Thomas4949** [comment]
好的，谢谢。
