### ISSUE TITLE
BBR之后安装上网工具失败

### ISSUE THREAD

**Issue by EdwinCXD** [waylybaye/HyperApp-Guide#111]
不安装BBR可正常安装
安装BBR后 一直提示create container failed

**Comment by waylybaye** [comment]
具体错误是什么？

**Comment by EdwinCXD** [comment]
![img_c0f67ffe2951-1](https://user-images.githubusercontent.com/16336523/28399689-3166125a-6d41-11e7-9452-4508f1c1c7ee.jpeg)

**Comment by waylybaye** [comment]
一定要先装 BBR 再装应用…

现在的话可以执行 `rm -rf /var/lib/aufs` 然后重新安装 SSR 就好了。

**Comment by EdwinCXD** [comment]
新开一个之后先装BBR 再装 还是报这个错误
![img_02482607369f-1](https://user-images.githubusercontent.com/16336523/28400702-81c5e04e-6d47-11e7-9fd5-cad3020f4b78.jpeg)

**Comment by waylybaye** [comment]
你是啥系统版本？看看 HyperApp 的要求支持么

**Comment by EdwinCXD** [comment]
CentOS 7
<img width="351" alt="tmp5de3ce28" src="https://user-images.githubusercontent.com/16336523/28400836-4cc56c56-6d48-11e7-99ba-642eed4b7082.png">

**Comment by waylybaye** [comment]
CentOS 7升级BBR会导致文件系统只读，运行命令重新挂载 `mount -o remount rw /`。 如果不是非常熟悉的话还是推荐用 Ubuntu。

**Comment by EdwinCXD** [comment]
请问是哪个ubuntu？
<img width="291" alt="tmp14f8391b" src="https://user-images.githubusercontent.com/16336523/28401641-da9f4ca4-6d4d-11e7-9061-586682b491ed.png">

**Comment by waylybaye** [comment]
最新的

**Comment by EdwinCXD** [comment]
好了 感谢😄
刚看到了联通检测那个
想问下TLS要怎么加？

**Comment by waylybaye** [comment]
翻这个仓库里的文档
