### ISSUE TITLE
请问是否有开发安卓版本的意向

### ISSUE THREAD

**Issue by xcz1997** [waylybaye/HyperApp-Guide#142]
很期待安卓版本的诞生

**Comment by waylybaye** [comment]
这要等到 Mac 版后面了……而且还不一定出不出……

**Comment by xcz1997** [comment]
我特地找来iOS设备购买一用，真的是很好用，省去了很多个人搭建成本，很不错的app，可惜我是开发安卓端的，几乎不用ios设备
