### ISSUE TITLE
苹果中国区下架了，已购买的在已购列表中也看不见了，咋办

### ISSUE THREAD

**Issue by yiranphp** [waylybaye/HyperApp-Guide#151]
苹果中国区下架了，已购买的在已购列表中也看不见了，咋办

**Comment by waylybaye** [comment]
我正在跟苹果申诉，目前还没有回复，可以先稍等下沟通结果。

**Comment by eyaeya** [comment]
@waylybaye 新版本更新时提示“此项目已不再提供”，请问我们怎么办？

**Comment by waylybaye** [comment]
https://www.hyperapp.fun/zh/faq.html

**Comment by alexluoli** [comment]
换区要取消Apple Music资格，这怎么办？

**Comment by alexluoli** [comment]
改区要取消Apple Music会员资格，然而我取消Music订阅后再改区、还是让我先“取消Apple Music会员资格”，请问可以怎样做？

**Comment by waylybaye** [comment]
有订阅和余额是无法转区的。至于这个“取消Apple Music会员资格”我还真不太清楚，我自己目前还没转区，也只听用户反馈需要取消 AM 订阅，倒不知道取消会员资格有啥影响。

**Comment by alexluoli** [comment]
我改到香港区了，下载还是要付费。
美国区太麻烦，要付款信息。
