### ISSUE TITLE
docker和一键安装脚本能否共存

### ISSUE THREAD

**Issue by flyingwhalefall** [waylybaye/HyperApp-Guide#162]
我原来在vps上用teddysun的一键安装脚本装了SSR，现在入手hyperapp，想试下ssr的docker，不知会不会矛盾冲突

**Comment by waylybaye** [comment]
当然可以，只要端口不重复就行

**Comment by flyingwhalefall** [comment]
谢谢，早上尝试成功，而且可以同时装多个v2ray，简单实现多用户，太棒了
