### ISSUE TITLE
nghttpx+squid配置HTTPS代理失败

### ISSUE THREAD

**Issue by flyingwhalefall** [waylybaye/HyperApp-Guide#176]
安装hyperapp的教程配置完，发现有些网站能上，Google/reuters等都不行 。
1）按照教程里配置，除了nghttpx端口因为VPS已经有V2RAY-TLS占用443端口，改为10086外，其他基本都是教程默认的。
2）nghttpx里的证书也没问题，使用certbot生成，同样HYPERAPP部署的V2RAY-TLS正常使用的crt和key。

![img_5383](https://user-images.githubusercontent.com/30478118/29154103-8f867e90-7dc4-11e7-944a-dba4c1fe7c26.PNG)
![img_5385](https://user-images.githubusercontent.com/30478118/29154104-8f89b8c6-7dc4-11e7-8543-2f4f8c712ac5.PNG)
![default](https://user-images.githubusercontent.com/30478118/29154106-8f9079e0-7dc4-11e7-85b3-dbbe5d63e8e4.JPG)
![2](https://user-images.githubusercontent.com/30478118/29154105-8f8e19a2-7dc4-11e7-8d74-c41249dd4376.JPG)

查看了下nghttpx的日志如下

2017-08-10T03:37:15.916Z 1 1 3ebc4768 NOTICE (shrpx.cc:854) Listening on 0.0.0.0:10086, tls
2017-08-10T03:37:15.917Z 1 1 3ebc4768 NOTICE (shrpx.cc:854) Listening on [::]:10086, tls
2017-08-10T03:37:15.917Z 1 1 3ebc4768 NOTICE (shrpx.cc:1297) Worker process [5] spawned
2017-08-10T03:37:15.917Z 1 1 3ebc4768 NOTICE (shrpx_worker_process.cc:213) Renew new ticket keys
2017-08-10T03:37:15.918Z 1 1 3ebc4768 NOTICE (shrpx_connection_handler.cc:311) [LISTEN:0x7ffd56cf64d0] Created worker thread #0
env: can't execute 'python': No such file or directory
2017-08-10T03:37:15.919Z 1 1 3ebc4768 WARN (shrpx_connection_handler.cc:610) ocsp query command for /certs/www.xxx.tk.crt failed: error=0, rstatus=7f00, status=127

似乎来看还是跟证书有关，不知到底什么问题，请大佬们帮忙看看，谢谢

**Comment by flyingwhalefall** [comment]
查了下ip

Your IP: 183.240.20.29, IP Location: China
# whois 183.240.20.29

inetnum:        183.192.0.0 - 183.255.255.255
netname:        CMNET
descr:          China Mobile Communications Corporation


看来压根没代理上。。。

**Comment by waylybaye** [comment]
先用
```http_proxy=http://hyperapp:hyperapp@ss.com:11111/ curl -v google.com```
测试下看看有没有问题。

**Comment by flyingwhalefall** [comment]
谢谢大佬及时提示，我是在搬瓦工centos 7 x64-bbr上搭建的
刚才用root登录XSHELL，提示

[root@host ~]# http_proxy=http://hyperapp:hyperapp@ss.com:11111/ curl -v google.com
* About to connect() to proxy ss.com port 11111 (#0)
*   Trying 194.105.56.170...
* Connection timed out
* Failed connect to ss.com:11111; Connection timed out
* Closing connection 0
curl: (7) Failed connect to ss.com:11111; Connection timed out
[root@host ~]#

**Comment by waylybaye** [comment]
把 `ss.com:111` 换成你自己的代理地址啊！

**Comment by flyingwhalefall** [comment]
不好意思，没学过计算机的我真是大白啊。。
* About to connect() to proxy www.xxx.tk port 10086 (#0)
*   Trying x.x.x.x...
* Connected to www.xxx.tk (x.x.x.x) port 10086 (#0)
* Proxy auth using Basic with user 'hyperapp'
> GET HTTP://google.com/ HTTP/1.1
> Proxy-Authorization: Basic aHlwZXJhcHA6aHlwZXJhcHA=
> User-Agent: curl/7.29.0
> Host: google.com
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Empty reply from server
* Connection #0 to host www.xxx.tk left intact
curl: (52) Empty reply from server
[root@host ~]# 


麻烦看看
