### ISSUE TITLE
“关于 Nginx 的上传限制”有个指令应该写错了

### ISSUE THREAD

**Issue by Qinyongr** [waylybaye/HyperApp-Guide#209]
常见错误指引中的[关于 Nginx 的上传限制](https://www.hyperapp.fun/zh/faq.html )，“你可以新建一个文件 `/srv/docker/vhost.d/default`”，好像应该是`/srv/docker/nginx/vhost.d/default`。

**Comment by waylybaye** [comment]
感谢指正，其实你也可以直接点页面左上角的 `Edit` 修改后提个PR的  😂
