### ISSUE TITLE
关于UDP转发

### ISSUE THREAD

**Issue by Egolas** [waylybaye/HyperApp-Guide#218]
ssr似乎没有支持udp转发？
请问可以打开吗？
如果可以，通过怎样的设置可以打开呢？

**Comment by waylybaye** [comment]
默认开了的，不过你如果有防火墙的话需要把 UDP 加上。

**Comment by Egolas** [comment]
我看了一下ufw状态是inactive
然后用iptables --list看了一下，有这么一段

`Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:7290
ACCEPT     udp  --  anywhere             172.17.0.2           udp dpt:7290
`

这是防火墙有允许udp通过吗？
但我测试了一下还是没有udp转发……

**Comment by waylybaye** [comment]
防火墙有两种，一个是Linux系统的防火墙，一个是主机商的防火墙。不同的厂商不太一样，你要两个都检查下…
