### ISSUE TITLE
HyperApp-Hugo

### ISSUE THREAD

**Issue by LeeGo486** [waylybaye/HyperApp-Guide#221]
使用HyperApp安装Hugo，logs：Unable to locate Config file. Perhaps you need to create a new site. Run `hugo help new` for details. (Config File 'config' Not Found in "[/src]")
请问是什么问题

**Comment by waylybaye** [comment]
这是正常的，你需要将本地的hugow文件夹传上去

**Comment by LeeGo486** [comment]
@waylybaye  ：首先感谢你的回答，还有点疑问，你指的hugow文件夹 是指“Mysite”这个文件夹吗？ 我按照教程这个文件夹上传了的。并更新配置...

**Comment by waylybaye** [comment]
你看这个教程了么…这儿有解释的 https://www.hyperapp.fun/zh/static-site.html

**Comment by LeeGo486** [comment]
谢谢,搞定了.   我的问题是Hugo 文件夹下是Mysite (Hugo/Mysite)。而不是(Hugo/config.toml,XXX,XXX等等)
