### ISSUE TITLE
关于Anyconnect 断流问题

### ISSUE THREAD

**Issue by phoenixruyi** [waylybaye/HyperApp-Guide#226]
用全家桶安装的ocserv，手机端用anyconnect来连接一切正常。但用mac连接时大概每隔4分钟重连。
当过去半个小时左右会发生掉线无法重连的情况，这时只有退出客户端重新启动才能恢复。

会不会与ocserv的配置有关呢？我在网络上找了一份配置文件不知是否有参考意义 https://bitbucket.org/snippets/halczy/aopxK

**Comment by waylybaye** [comment]
Mac 的每4分钟重连过程中并不影响上网吧。半个小时会掉线的话我估计可能是被干扰了。

**Comment by MJNSFAROA** [comment]
八爷，是的，重连过程不影响上网。

掉线那个有可能被干扰，但是奇怪的是同一时刻同一网路环境下的iOS端Anyconnect却没有掉线，它那边一切正常。只有mac端的大约在30分钟左右无法重连。

Mac 端的Anyconnect 版本号是4.5.02033，会和我用的客户端有关系吗？
