### ISSUE TITLE
GCE 开启 BBR 加速之后显示「无法连接」

### ISSUE THREAD

**Issue by hoginwang** [waylybaye/HyperApp-Guide#259]
按教程（https://github.com/waylybaye/HyperApp-Guide/blob/master/zh/proxy/get-started.md ）先点按脚本开启BBR，显示 done、Shell closed 后关闭窗口。之后一直无法连接，即使重头再来也是卡在这一步，无法进行下一步。

**Comment by waylybaye** [comment]
先手动开启吧，最新的系统内核跟脚本冲突

https://github.com/iMeiji/shadowsocks_install/wiki/%E5%BC%80%E5%90%AFTCP-BBR%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95
