### ISSUE TITLE
无法使用科学上网ss

### ISSUE THREAD

**Issue by WaterChan** [waylybaye/HyperApp-Guide#262]
使用谷歌的GCP，成功部署过ss并正常使用半年，但一个月前突然无法使用，我删了应用，重新建一个用了80端口，变正常了，但半个月以后又不行了，是不是80端口也不行的原因？

**Comment by waylybaye** [comment]
应该被墙了，加一下混淆试试

**Comment by WaterChan** [comment]
@waylybaye 我在telnet过443和80都不通，应该是被墙了，加混淆也不行，是否要用其他科学方法去创建防火墙规则

**Comment by waylybaye** [comment]
还个IP咯，然后使用时候注意点
