### ISSUE TITLE
PHP伪静态

### ISSUE THREAD

**Issue by Hiyuu-cc** [waylybaye/HyperApp-Guide#271]
请问一下使用PHP应用安装的网站怎么开启伪静态？ 找不到Nginx.conf

**Comment by waylybaye** [comment]
目前Nginx Proxy不支持伪静态，需要的话可以手动配 Nginx

**Comment by MMBBao** [comment]
> 目前Nginx Proxy不支持伪静态，需要的话可以手动配 Nginx

PHP装的Web没有Nginx文件啊

**Comment by MMBBao** [comment]
> 目前Nginx Proxy不支持伪静态，需要的话可以手动配 Nginx

大佬？ Nginx文件在哪啊
