### ISSUE TITLE
Nginx SSL Support使用ACMEv1，不能再更新证书，请更新docker镜像

### ISSUE THREAD

**Issue by cquzc** [waylybaye/HyperApp-Guide#281]
收到Let's encrypt的邮件，ACMEv1已经不能为域名申请SSL证书了，请更新到支持ACMEv2镜像

**Comment by waylybaye** [comment]
pull image 并且 update config 一下就好了

**Comment by cquzc** [comment]
> pull image 并且 update config 一下就好了

好了，谢谢
