### ISSUE TITLE
jekyll 安装失败

### ISSUE THREAD

**Issue by siwting** [waylybaye/HyperApp-Guide#40]
其他应用可以正常安装。
具体日志如下：
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.017 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.021 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.02 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.031 seconds.
[33mConfiguration file: none[0m
 Auto-regeneration: enabled for '/srv/jekyll'
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.014 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.016 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.026 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.018 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.02 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
[33mConfiguration file: none[0m
[33mConfiguration file: none[0m
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.019 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
[33mConfiguration file: none[0m
jekyll 3.4.3 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site

**Comment by waylybaye** [comment]
目测是用户权限错误，你有没有尝试过把本地的 jekyll 目录直接复制到服务器的 /srv/docker/jekyll 里面看看是否可以？
