### ISSUE TITLE
希望能增加进入目标容器执行命令的功能

### ISSUE THREAD

**Issue by fanvinga** [waylybaye/HyperApp-Guide#74]
例如下列命令可以进入我的httpd容器：
docker exec -it docker-283f5c bash
这样的命令有助于我进入容器中执行一些修改配置文件的要求.谢谢

**Comment by waylybaye** [comment]
嗯，我打算在 Docker 监控那里加一个菜单项，叫做 `Shell` 吧，点击可以打开终端进入容器的 sh

**Comment by fanvinga** [comment]
这样很棒.但我的个人意见是加在应用的选项里面,与安装/启动等选项并列,这样的话,我觉得就不用我在监控里面选择要进入哪个容器的shell.而且可能这样子开发难度还要容易一些?纯粹个人意见:)

**Comment by waylybaye** [comment]
我也想加那个里面，但是那个菜单的选项实在是太多了……小屏幕上一屏都快显示不完了……

**Comment by fanvinga** [comment]
我刚刚看了一下.有个主意.在docker资源监控界面.就是看容器资源占用那里.那个的点击菜单的子菜单现在只有三个选项.我觉得加那里会比较好做：）

**Comment by waylybaye** [comment]
嗯，我刚刚说的就是在这个地方…

**Comment by waylybaye** [comment]
Added in 2.8
