### ISSUE TITLE
希望能增加编辑应用商店中应用的启动命令

### ISSUE THREAD

**Issue by fanvinga** [waylybaye/HyperApp-Guide#75]
我举个例子.
比如说商店中的Resilio Sync.它默认能够访问的目录就是/srv/docker/ResilioSync/folders/.但是如果我想利用这个应用来同步其他目录的话.现有的选项是做不到的.
如果要做到我可以这样子修改容器的启动命令
加入-v /root:/root
把宿主的root目录挂载到容器的root目录下面.使得容器也可以访问宿主机的root目录(前提是权限允许)
我希望能够像自定义容器里面的Command选项一样可以自己附加命令:)
谢谢:)

**Comment by waylybaye** [comment]
这个现在也可以的啊，你把 `/srv/docker/RC` 手动改成  `/root` 就好了嘛

**Comment by fanvinga** [comment]
按照您的方法是不行的.因为这样子的话sync目录是root的子目录.而RS对sync目录只有只读权限.对sync的子目录folders才有写入权限.然后又不能使用软连接.所以还是访问不了root的目录.不知道做一个那样的Command框是否十分困难？

**Comment by waylybaye** [comment]
RS权限的问题我还没仔细研究，不过docker本事是用root跑的，其实这个地方就是用来生成 `-v` 参数的，会自动把你选的路径挂载到容器里面一个路径上。所以如果你只是想要一个 `-v` 参数的话这个应该是没问题的，只不过 RS 这个只挂载了 `/mnt/sync` 这个容器内的路径。

自定义Command的话现在是推荐用商店里的 `Docker Image`，这个可以手动填写所有参数……

**Comment by fanvinga** [comment]
其实我这么想是因为如果用商店里面的Docker Image的话.要配置所有参数.毕竟我只是linux新手,想要配置到效果跟应用商店那种程度很麻烦(技术不行/捂脸),只是增添一个或者两个参数的话用应用商店里面的会好很多,我觉得这样子应该能方便到不少有这类需求的人吧.不管怎么做.谢谢你做的应用:)
