### ISSUE TITLE
请教作者关于利用Nginx容器

### ISSUE THREAD

**Issue by fanvinga** [waylybaye/HyperApp-Guide#76]
不好意思又来叨扰你了.就是比如说我在宿主机上架设了一个服务.我想通过Nginx容器来反向代理它.不知道该怎么做呢

**Comment by waylybaye** [comment]
啊，这个就有点麻烦了，你可以在  `/etc/nginx/conf.d/` 下面建一个 `.conf` 文件就好了，但是这儿没有保存在宿主机上所以比较容易丢失。

**Comment by waylybaye** [comment]
这个就得自己配置了，你可以用let's encrypt 的命令行生成免费的，也可以买商业证书……
