### ISSUE TITLE
app里一直出现密钥认证失败

### ISSUE THREAD

**Issue by thallium** [waylybaye/HyperApp-Guide#80]
我是看的少数派里的那个教程，按照里面说的解决办法弄了好多次了，还是认证失败

**Comment by waylybaye** [comment]
是秘钥认证失败？你可以按下面的方式排查下：
1. 服务器 IP 是否变了
2. 服务器的用户名和GCP后台元数据 SSH 里面的用户名是否一致。

**Comment by txl263** [comment]
同密钥认证失败，同手机用终端加密钥的方法可以登录但是HyperAPP里密钥认证失败，DigitalOcean和UltraVPS都失败。
