### ISSUE TITLE
HyperApp的docker-compose能公开学习下吗

### ISSUE THREAD

**Issue by jpacg** [waylybaye/HyperApp-Guide#82]
docker学过一段时间，只会简单的使用，实践了下《如何一键搭建支持 https 的网站》，想学一下docker-compose.yml是怎么写的，但在git的仓库都没找到，不知道作者能不能公开让学习一下？

**Comment by waylybaye** [comment]
其实没有 docker-compose.yml 因为执行方法是不一样的，HyperApp 是通过 SSH 直接创建容器的，没用编排工具，或者说 HyperApop 就是一个图形化的编排工具…
