### ISSUE TITLE
HyperApp的ss-libev是否支持udp?

### ISSUE THREAD

**Issue by Thomas4949** [waylybaye/HyperApp-Guide#98]
我看了下shadowsocks-libev在Github上的说明，有这么一句：

> It's quite easy to use shadowsocks and KCP together with kcptun.
The goal of shadowsocks over KCP is to provide a fully configurable, **UDP based protocol** to improve poor connections, e.g. a high packet loss 3G network.

是否可以理解为shadowsocks-libev若想使用udp，必须同时使用kcptun？

而HyperApp对于shadowsocks-libev的配置页面没有像“开启简单混淆”那样的选项，说明HyperApp上没有加上kcptun，也就无法使用udp协议，以及其它一些kcp所能带来的好处。

如果可以，开发者可否加上kcptun？因为有使用udp的相关需求。

**Comment by waylybaye** [comment]
不是，本身就支持 UDP，UDP ≠ KCP。商店里有 kcptun 你如果想用的话也可以配合一起用。

**Comment by Thomas4949** [comment]
这样啊，好的，谢谢。
